default_context:
  project_name: 'potato-ota'
  project_slug: 'potato-ota'
  domain_main: 'api.potatoproject.co'
  domain_staging: 'stag.api.potatoproject.co'
  docker_swarm_stack_name_main: 'potato-ota'
  docker_swarm_stack_name_staging: 'stag-potato-ota'
  secret_key: 'd68b7aa1f87a9e7195836af5e2cd6a3325b09023478d217a014ae9cec592607a'
  first_superuser: 'admin@api.potatoproject.co'
  first_superuser_password: '41583fc63cf7aaff936731d98b8f938f2c585d0be26d4537796d3faafe126d0c'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.api.potatoproject.co", "https://stag.api.potatoproject.co", "https://api.potatoproject.co", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@api.potatoproject.co'
  postgres_password: 'c3f59cb2303f50c4856565dbe617c805b06bd3f895121ce188d62ceb124cc484'
  pgadmin_default_user: 'admin@potatoproject.co'
  pgadmin_default_user_password: '41583fc63cf7aaff936731d98b8f938f2c585d0be26d4537796d3faafe126d0c'
  traefik_constraint_tag: 'api.potatoproject.co'
  traefik_constraint_tag_staging: 'stag.api.potatoproject.co'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:41583fc63cf7aaff936731d98b8f938f2c585d0be26d4537796d3faafe126d0c'
  sentry_dsn: ''
  docker_image_prefix: 'ota'
  docker_image_backend: 'otabackend'
  docker_image_celeryworker: 'otaceleryworker'
  docker_image_frontend: 'otafrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
